server:
  port : 8082
  
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=microservices&binaryTransfer=true&reWriteBatchedInserts=true&stringtype=unspecified
    username : postgres
    password : admin
    driver-class-name: org.postgresql.Driver
  jpa :
    hibernate :
      ddl-auto : update
    show-sql : true
  application:
    name: HOTEL-SERVICE
    
  config:
    import: optional:configserver:http://localhost:8085

#Commenting below eureka service registry configuration as it will be fetched from remote config server configured above

#eureka:
#  instance:
#    prefer-ip-address: true
#  client :
#    fetch-registry : true
#    register-with-eureka : true
#    service-url:
#      defaultZone : http://localhost:8761/eureka